### ISSUE TITLE
Fix for Ubuntu 24.04

### ISSUE THREAD

**Issue by benne3333** [nlpsuge/gnome-shell-extension-another-window-session-manager#105]
After upgrade from 23.10 to 24.04 with GNOME 46 the extension doesn't work. Manual install with current REPO (GNOME 46 fix) does not work either.
Extension is deactivated as "not compatible with current GNOME version 46".

**Comment by benne3333** [comment]
Changing the lines mentioned in @ #103 doesn't help.

**Comment by nosut** [comment]
Not sure if it will work for you but after I made the changes in #103 it was also still telling me it was not compatible. So I went into the dconf settings org>gnome>shell and enabled the 'Disable-extention-version-validation' setting and now it is working again.

**Comment by Rantyrant** [comment]
> Not sure if it will work for you but after I made the changes in #103 it was also still telling me it was not compatible. So I went into the dconf settings org>gnome>shell and enabled the 'Disable-extention-version-validation' setting and now it is working again.

You could also just bump the version number in the metadata file.
E.g. change `shell-version` from 45 to 46, and then `"version"` from 46 to 47.

**Comment by nlpsuge** [comment]
@benne3333 Hi, a new version that supports Gnome 46 has been approved. I'm closing this issue now. Please feel free to reopen it if you encounter any issues with the new version.
