### ISSUE TITLE
Support saving/restoring window size and position

### ISSUE THREAD

**Issue by passcod** [nlpsuge/gnome-shell-extension-another-window-session-manager#17]
This is only to make an issue for tracking when this is done :)

From the extensions page:

> Hi oshikuru,
>
> Saving/restoring size and position is buggy, it does not work expectedly, so I remove it. But it should be a must feature, I'll fix it in the future.
> 
> Thanks for support. :)

**Comment by nlpsuge** [comment]
@passcod 

I have published a new version which supports saving and restoring window size and position to https://extensions.gnome.org/extension/4709/another-window-session-manager. I suggest to read the [Known issues](https://github.com/nlpsuge/gnome-shell-extension-another-window-session-manager#known-issues) first.

**Comment by passcod** [comment]
These are some _spicy_ issues, but well done nonetheless! Looking forward to trying this out

**Comment by nlpsuge** [comment]
> These are some _spicy_ issues

Feel free to report them.  :)

**Comment by khimaros** [comment]
it looks like we are both trying to solve this problem! your approach looks really solid, and I suspect i can learn something from it. please contact me if you'd like to collaborate. email is in my GH profile!

**Comment by nlpsuge** [comment]
@khimaros 

I've sent an email to you. :)
