### ISSUE TITLE
Restore automatically the "maximizedness" state of the window

### ISSUE THREAD

**Issue by bogado** [nlpsuge/gnome-shell-extension-another-window-session-manager#40]
For ultra wide monitors it's common to have windows maximized to the left and other maximized to the right with different proportions. Even though the size and locations are restored correctly this state is not restored, so when I try to change the proportion of the windows this don't work as expected.

**Comment by nlpsuge** [comment]
Yes, it does have this issue. I remember it's very tricky, strange behavior when a window is maximized to the edge and to restore this state is not possible ... Maybe I should check this issue again.

**Comment by nlpsuge** [comment]
> I try to change the proportion of the windows this don't work as expected.

Could you please explain how you change proportion of the windows in case we are not on the same page. :)

**Comment by bogado** [comment]
When you have two windows one maximized to the left and another to the right you can drag the vertical intersection of the windows so the division is not on the exact middle of the screen.

**Comment by nlpsuge** [comment]
OK, I understand.

Thanks for the clarification. :)

**Comment by nlpsuge** [comment]
I consider this issue as a feature request. 

Because you actually want to save and restore the `edge tiling` state, which is not supported by this extension currently.

**Comment by nlpsuge** [comment]
This feature has been released in latest version 25.
