### ISSUE TITLE
Delete session is not working

### ISSUE THREAD

**Issue by curiousercreative** [nlpsuge/gnome-shell-extension-another-window-session-manager#42]
1. Click the shell extension icon in the top bar
2. Save a session if a custom session doesn't exist
3. Click delete button for custom session
    Expected result: session should be deleted from filesystem and removed from the session menu
    Actual result: nothing

Pop!_OS 22.04, GNOME 42, X11

**Comment by nlpsuge** [comment]
Yeah, it's a bug which was introduced last month. I'll release a fix as soon as possible.

**Comment by nlpsuge** [comment]
The fix has been approved on the [E.G.O](https://extensions.gnome.org/extension/4709/another-window-session-manager/).
