### ISSUE TITLE
Arch Linux Gnome Shell 42.2 - freezing when this extension is enabled

### ISSUE THREAD

**Issue by yawor** [nlpsuge/gnome-shell-extension-another-window-session-manager#47]
Hi,

After recent system update I've noticed that when this extension is enabled, the gnome freezes for some time (from few to tens of seconds) when logging in or unlocking the screen. Also restarting the shell using Alt+F2 and typing r causes the shell to freeze.

I've decided to test if it's one of the extensions I'm using and I've disabled all of them on by one and the behaviour stopped after disabling Another Window Session Manager. To check if it's maybe a conflict with another extension, I've kept all the other disabled and the freezing comes back when only this extension is active.

The extension is great and I've been using it without any issues for some time now. Also other than freezing the shell, the extension still works as advertised.

There are no errors regarding this extension in the journal. Please let me know if there's any way to debug this. I'm not familiar with creating/debugging gnome extensions so I need some guidance to be able to give you more details.

**Comment by nlpsuge** [comment]
I'll upload a fix version to the https://extensions.gnome.org/ soon.
