### ISSUE TITLE
Random crashes

### ISSUE THREAD

**Issue by kabe-inc** [nlpsuge/gnome-shell-extension-another-window-session-manager#56]
The extension works but randomly crashes during a session,whether it is used or not. 

The following error message is shown in Extensions Manager:

`Version 25`
`this._runningSaveCancelableMap is undefined`

My system:  
>Gnome v 42.4
>Endeavour OS

**Comment by danmullen** [comment]
I'm having the same issue in Gnome 42, Fedora 36.  Only started happening in the last week.

**Comment by nlpsuge** [comment]
> `this._runningSaveCancelableMap is undefined`

Please attach the error stack too, you can find it in the output of `journalctl -r /usr/bin/{gjs,gnome-shell}`.

**Comment by nlpsuge** [comment]
@danmullen @kabe-inc I think disable `Stash and restore` in `Restore sessions` Tab might let you get rid of this issue before it got fixed.
![image](https://user-images.githubusercontent.com/2271720/187964149-1a53f779-e450-4bd6-9aec-c74ebb147fba.png)

**Comment by danmullen** [comment]
> I think disable `Stash and restore` in `Restore sessions` Tab might let you get rid of this issue before it got fixed.

Changing that setting and rebooting hasn't stopped the crashes.

**Comment by danmullen** [comment]
Redacted my username from the log snippet below...
```
JS ERROR: Extension another-window-session-manager@gmail.com: TypeError: this._runningSaveCancelableMap is undefined
  _cancelAllRunningSave@/home/<username>/.local/share/gnome-shell/extensions/another-window-session-manager@gmail.com/openWindowsTracker.js:331:35
  destroy@/home/<username>/.local/share/gnome-shell/extensions/another-window-session-manager@gmail.com/openWindowsTracker.js:339:14
  disable@/home/<username>/.local/share/gnome-shell/extensions/another-window-session-manager@gmail.com/extension.js:41:29
  _callExtensionDisable@resource:///org/gnome/shell/ui/extensionSystem.js:123:32
  _onEnabledExtensionsChanged/<@resource:///org/gnome/shell/ui/extensionSystem.js:534:45
  _onEnabledExtensionsChanged@resource:///org/gnome/shell/ui/extensionSystem.js:534:24
  _sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:656:14
  _emit@resource:///org/gnome/gjs/modules/core/_signals.js:114:47
  _sync@resource:///org/gnome/shell/ui/sessionMode.js:202:14
  pushMode@resource:///org/gnome/shell/ui/sessionMode.js:161:14
  activate@resource:///org/gnome/shell/ui/screenShield.js:614:34
  lock@resource:///org/gnome/shell/ui/screenShield.js:660:14
  LockAsync@resource:///org/gnome/shell/ui/shellDBus.js:519:28
  _handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:354:35
  _wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:387:34
```

**Comment by kabe-inc** [comment]
My journalctl log:

>Sep 01 08:56:00 endeavour gnome-shell[1603]: JS ERROR: Extension another-window-session-manager@gmail.com: TypeError: this._runningSaveCancelableMap is undefined
                                             _cancelAllRunningSave@/home/-----/.local/share/gnome-shell/extensions/another-window-session-manager@gmail.com/openWindowsTracker.js:331:35
                                             destroy@/home/-----/.local/share/gnome-shell/extensions/another-window-session-manager@gmail.com/openWindowsTracker.js:339:14
                                             disable@/home/-----/.local/share/gnome-shell/extensions/another-window-session-manager@gmail.com/extension.js:41:29
                                             _callExtensionDisable@resource:///org/gnome/shell/ui/extensionSystem.js:123:32
                                             _onEnabledExtensionsChanged/<@resource:///org/gnome/shell/ui/extensionSystem.js:534:45
                                             _onEnabledExtensionsChanged@resource:///org/gnome/shell/ui/extensionSystem.js:534:24
                                             _sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:656:14
                                             _emit@resource:///org/gnome/gjs/modules/core/_signals.js:114:47
                                             _sync@resource:///org/gnome/shell/ui/sessionMode.js:202:14
                                             pushMode@resource:///org/gnome/shell/ui/sessionMode.js:161:14
                                             activate@resource:///org/gnome/shell/ui/screenShield.js:614:34
                                             _onLongLightbox@resource:///org/gnome/shell/ui/screenShield.js:333:18
                                             onComplete@resource:///org/gnome/shell/ui/lightbox.js:198:18
                                             _makeEaseCallback/<@resource:///org/gnome/shell/ui/environment.js:153:13
                                             _easeActor/<@resource:///org/gnome/shell/ui/environment.js:240:64
                                             
And yes, I'm using Wayland.

**Comment by danmullen** [comment]
> @danmullen OK, I see. 
> 
> So you both (@danmullen @kabe-inc ) are using Wayland?

Confirmed, I'm using Wayland.

**Comment by nlpsuge** [comment]
I will fix this issue later today or tomorrow and release a fix as soon as possible.

By the way, I think this issue happens when the extension disabled, in three cases:
* When the screen locked
* When you disable it manually in the Extensions app
* When uninstall it

**Comment by kabe-inc** [comment]
Can confirm the extension crashes on these two events, even with `Stash and Restore` disabled in settings:
 * When the screen locked
 * When you disable it manually in the Extensions app

**Comment by danmullen** [comment]
I haven't manually disabled or uninstalled it, so I presume it's the screen locking that's doing it.

**Comment by nlpsuge** [comment]
@danmullen @kabe-inc 

The fix has been published on https://extensions.gnome.org/extension/4709/another-window-session-manager/ and been approved. You might have received the update notification.
