### ISSUE TITLE
Firefox's windows restore crashes GNOME after its recent update in Fedora

### ISSUE THREAD

**Issue by areksobiczewski** [nlpsuge/gnome-shell-extension-another-window-session-manager#65]
One of my recent gnome updates* somehow impacted AWSM in a way that it's not able to restore Firefox's windows at all, resulting in gnome crash, preceded with gnome-shell high cpu usage during which gnome is completely unresponsive to the user, finnaly resulting in gnome auto crash / restore.
The problem remains even if Firefox has been opened before using windows restore function from AWSM.
The problem remains regardless of whether Firefox is set to restore its own session or not.

*) No more than the last two updates from gnome-shell-42.6-1.fc36

My AWSM settigns:
- No "close by rules" installed, the option is set off
- Everything swithed off in the "Restore session": no startup auto restore, no tiling restore, no raising windows together, no stashing.

My system:
- AWSM version 30
- Fedora 36
- GNOME 42.4, gnome-shell-42.6-1.fc36
- Firefox 107.0, 4.fc36 -- installed as RPM.

Logs:
- AWSM's debug log. 
[log messages - AWSM debug.txt](https://github.com/nlpsuge/gnome-shell-extension-another-window-session-manager/files/10153331/log.messages.-.AWSM.debug.txt)
- AWSM's config file for a session which restoring gives errors.
[AWSM Recently Closed Session config.txt.](https://github.com/nlpsuge/gnome-shell-extension-another-window-session-manager/files/10153335/AWSM.Recently.Closed.Session.config.txt)
- System log for Firefox during the problem happening.
[log messages - Firefox.txt](https://github.com/nlpsuge/gnome-shell-extension-another-window-session-manager/files/10153336/log.messages.-.Firefox.txt)
- System log for GNOME during the problem happening.
[log messages - gnome.txt](https://github.com/nlpsuge/gnome-shell-extension-another-window-session-manager/files/10153340/log.messages.-.gnome.txt)

**Comment by nlpsuge** [comment]
Can you launch Firefox and use it normally if AWSM is disabled?

**Comment by juanvalino** [comment]
Similar problem here. Last fedora updates changed something and now the extension freezes gnome shell after a while.

**Comment by areksobiczewski** [comment]
I promise to fulfill the information nlpsuge has asked for (plus some additional tests). Just bear with me (I've got some other work, unexpected and urgent to finish). Don't close this ticket.

**Comment by nlpsuge** [comment]
@areksobiczewski  Hi, I didn't find useful information that can be used to locate the cause from your uploaded logs. And I'll check them again in case I missed something.

@juanvalino @areksobiczewski Could you please test the master branch? https://github.com/nlpsuge/gnome-shell-extension-another-window-session-manager/commit/6d3cd3982abb6af8744823a1344e025ca654773f might have fixed this issue.

**Comment by juanvalino** [comment]
@nlpsuge I've been testing master barnch for a while and seems to work.

**Comment by juanvalino** [comment]
@nlpsuge this friday I'll work all morning with master branch enabled to get a better/longer test, but master branch seems to work

**Comment by areksobiczewski** [comment]
I'm also happy to report that the changes mentioned by @nlpsuge above are working for the problem I've initially reported. Super cool! Thank you.

Thank you @juanvalino for testing it. Your comment above encouraged me to do the same and that works for me. Cool.

**Comment by nlpsuge** [comment]
I uploaded an official version to E.G.O just now. Waiting for approval.

**Comment by nlpsuge** [comment]
> I uploaded an official version to E.G.O just now. Waiting for approval.

Approved.
