### ISSUE TITLE
As of today it doesn't work because of "Requiring GTop, version none: Typelib file for namespace 'GTop' (any version) not found"

### ISSUE THREAD

**Issue by NinjaTurtle007** [nlpsuge/gnome-shell-extension-another-window-session-manager#69]
I think it was due to update after restart yesterday and today it doesn't start with this message in the Extensions app. Removing and adding it doesn't help.

**Comment by Whats-the-time** [comment]
Same issue here after update on Pop!_OS 22.04 today.

**Comment by Whats-the-time** [comment]
Installing gir1.2-gtop-2.0 seemed to fix it for me.

**Comment by NinjaTurtle007** [comment]
seems to fix it for me also, thanks @Whats-the-time !

**Comment by curiousercreative** [comment]
Just to say that my Pop! 22.04 systems also reproduce this issue.

**Comment by noweasyjay** [comment]
typelib-1_0-GTop-2_0 works for opensuse

**Comment by nashamri** [comment]
This fixes it for me if you are using NixOS:
`services.xserver.desktopManager.gnome.sessionPath = [ pkgs.libgtop ];`

**Comment by beardChamp** [comment]
> Installing gir1.2-gtop-2.0 seemed to fix it for me.

Installing this resolved my issues on Ubuntu 22.04

**Comment by RemcoSchrijver** [comment]
Maybe add this as instructions for dependencies on debian based systems in the readme?

**Comment by nlpsuge** [comment]
@RemcoSchrijver 

I just merged a PR which describes this dependency and installation instructions, you can find it here:

https://github.com/nlpsuge/gnome-shell-extension-another-window-session-manager#dependencies

But I'm mainly using Fedora daily, welcome to complete it.

**Comment by RemcoSchrijver** [comment]
@nlpsuge 
Yeah lgtm, added a small change that removed the Pop!_OS reference in #76 because it is a Ubuntu derivative anyway so the same installation methods should work. Think with that this issue can be closed?

**Comment by nlpsuge** [comment]
@RemcoSchrijver 

https://github.com/nlpsuge/gnome-shell-extension-another-window-session-manager/pull/76 has been merged to main branch, I close this issue then.
