### ISSUE TITLE
ydotoool.service not found

### ISSUE THREAD

**Issue by rwjack** [nlpsuge/gnome-shell-extension-another-window-session-manager#83]
I tried enabling the `Auto close session` option today, but I keep getting this error and nothing happens.

I installed `apt install ydotool`, but no avail. 
`ydotool/jammy,now 0.1.8-3 amd64 [installed]` <- doesn't seem to be above 1.0.0

Any ideas?

![image](https://github.com/nlpsuge/gnome-shell-extension-another-window-session-manager/assets/59068073/d3bf9518-2464-419c-b06e-31117c132c61)

**Comment by rwjack** [comment]
So I just copy it to `/usr/local/bin` and then what? The service still doesn't exist

**Comment by rwjack** [comment]
https://github.com/ReimuNotMoe/ydotool/blob/master/Daemon/ydotool.service.in

I see this, but the way forward is kind of confusing.

Do I need the service or not? Will AWSM start it? Where do I put it initially, in the home dir or in /etc/systemd/system?

**Comment by nlpsuge** [comment]
@rwjack Is `Close by rules` (just under `Auto close session` ) enable or not?

**Comment by rwjack** [comment]
enabled

**Comment by rwjack** [comment]
Seems to working now after a regular reboot

**Comment by freddyw** [comment]
FWIW, I had the same issue. Copying the ydotool.service file from /usr/lib/systemd/system to /usr/lib/systemd/user resolved it for me.

**Comment by nlpsuge** [comment]
Hi, I'll close this issue now, feel free to reopen it if necessary.


For those who are not sure how to setup `ydotoool`, please look at https://github.com/nlpsuge/gnome-shell-extension-another-window-session-manager#how-to-make-close-by-rules-work
