### ISSUE TITLE
Add an option to hide the extension in the top panel

### ISSUE THREAD

**Issue by nlpsuge** [nlpsuge/gnome-shell-extension-another-window-session-manager#86]
### Discussed in https://github.com/nlpsuge/gnome-shell-extension-another-window-session-manager/discussions/85

<div type='discussions-op-text'>

<sup>Originally posted by **Netherquark** July  2, 2023</sup>
For my usecase, I'm only going to use the save session on logout, and restore session automatically settings. I don't need to have the extension in my top panel 24x7, because though its running 24x7, it'll do everything it needs to automatically.

Would it be possible to add this option similar to how the "Emoji Selector" extension has it?

For reference:

![image](https://github.com/nlpsuge/gnome-shell-extension-another-window-session-manager/assets/65618735/903182d6-a909-411f-ad65-c0c372145b14)
</div>

**Comment by android272** [comment]
Yeah I am in the same boat, I just want it to save my session on shut down and restore automatically. I don't need the icon in the top bar.

**Comment by nlpsuge** [comment]
![image](https://github.com/nlpsuge/gnome-shell-extension-another-window-session-manager/assets/2271720/a4ab1b3c-5d81-4197-84e8-ec12e55408d4)

An option is added to the `General` tab in Preferences as the above screenshot shows. This changing will be published to https://extensions.gnome.org later.
