### ISSUE TITLE
When restoring the windows after a reboot or logoff/logon I get the following message regarding the Gnome Terminal app

### ISSUE THREAD

**Issue by logicito** [nlpsuge/gnome-shell-extension-another-window-session-manager#87]
![image](https://github.com/nlpsuge/gnome-shell-extension-another-window-session-manager/assets/70069626/53bd0a7e-c08c-4e31-8934-662421bf6e56)

Any idea of the potential root cause for this and how to fix it?

**Comment by nlpsuge** [comment]
> ![image](https://user-images.githubusercontent.com/70069626/252120757-53bd0a7e-c08c-4e31-8934-662421bf6e56.png)
> 

Please check folder `/home/l/.config/another-window-session-manager/currentSession`, there you may find some folders whose `Modified time` is not today. 

For example, on my machine:
![image](https://github.com/nlpsuge/gnome-shell-extension-another-window-session-manager/assets/2271720/a98b6801-c1d9-4bb3-b097-0f958ea0f6e1)
As you can see, folder `Gnome-shell` has a session file but its `cmd` and `desktop_file_id`, so that's not possible to restore the app `Gnome-shell`. 

I think you can just ignore it.  But please check `/home/l/.config/another-window-session-manager/currentSession` at first.

**Comment by logicito** [comment]
I don't have the "l" directory within home, also there is no Gnome-shell folder, there is one named "null"

![Screenshot from 2023-07-15 20-58-23](https://github.com/nlpsuge/gnome-shell-extension-another-window-session-manager/assets/70069626/993c935f-11de-4db9-8ec9-059a0e180544)

**Comment by idevelop-app** [comment]
> folder `null` has been ignored during restore apps, see:
> 
> https://github.com/nlpsuge/gnome-shell-extension-another-window-session-manager/blob/e903f1e690e92f3aaea7f5f7f46dd16102748e44/restoreSession.js#L145-L148
> 
> > ![image](https://user-images.githubusercontent.com/70069626/252120757-53bd0a7e-c08c-4e31-8934-662421bf6e56.png)
> 
> I saw this error on my machine in the output of `journalctl -r` but not sure why, will look into it.

That folder should be the Gnome Terminal app (Shell) folder, for some reason it has been renamed to null

**Comment by nlpsuge** [comment]
Hi,
This is because it restores apps from `~/.config/another-window-session-manager/currentSession/summary.json`, which is not successful. 

I will push a new version to E.G.O. You can also test it using the `main` branch.

**Comment by logicito** [comment]
Thank you very much

**Comment by logicito** [comment]
> Hi,
> 
> This is because it restores apps from `~/.config/another-window-session-manager/currentSession/summary.json`, which is not successful. 
> 
> 
> 
> I will push a new version to E.G.O. You can also test it using the `main` branch.

I see version 39 in Gnome Extensions, is that the newest version? Github has 38, please could you confirm, thanks

**Comment by nlpsuge** [comment]
> > Hi,
> > This is because it restores apps from `~/.config/another-window-session-manager/currentSession/summary.json`, which is not successful.
> > I will push a new version to E.G.O. You can also test it using the `main` branch.
> 
> I see version 39 in Gnome Extensions, is that the newest version? Github has 38, please could you confirm, thanks

I forget to bump the version on Github, which should be 40, I have update it just now, see 17d4fd90f4193fd874be98cf7e644759e15e5fce.

**Comment by logicito** [comment]
Everytime I logout and login again Gnome Shell will crash, print screen below, If I disable the Extension no more crash:

![image](https://github.com/nlpsuge/gnome-shell-extension-another-window-session-manager/assets/70069626/66b13490-8eeb-41a4-abd5-f44e872203ad)

**Comment by logicito** [comment]
Update: Removed and Installed again the Extension, it is working fine now, I don't know what could have happened, any idea from the previous screenshot?

**Comment by nlpsuge** [comment]
![image](https://github.com/nlpsuge/gnome-shell-extension-another-window-session-manager/assets/2271720/54b167db-5c9f-4b68-84df-f32ce2869d7e)

Please upload the `var_log_messages` if you can.

**Comment by logicito** [comment]
I am no longer getting the error after I reinstalled it

**Comment by nlpsuge** [comment]
> I noticed a new version 41 today, anything specific added to the extension related to my last comment?

Version 41 fix the compatibility issues with Gnome 41, see https://github.com/nlpsuge/gnome-shell-extension-another-window-session-manager/issues/79
