### ISSUE TITLE
Restore session after startup

### ISSUE THREAD

**Issue by sojusnik** [nlpsuge/gnome-shell-extension-another-window-session-manager#9]
Would be very handy, if this extension could save all windows before a system shutdown and restore them after startup, with the same window size and position (including workspaces).

**Comment by nlpsuge** [comment]
Duplicate issue: https://github.com/nlpsuge/xsession-manager/issues/30


The current released version can restore windows to their associated workspace.

My priority is:
1)  Restore saved windows after startup, should popup a dialog with a timeout (can be set in the Preferences?), user can click Yes to confirm or click cancel to stop to restore in case no need to restore.
2) Restore window size and position. I have written this code but not well-tested, may not work at all. BTW, most app can restore their size and geometry on Gnome. Looks Shell API does not support this, not sure, I need more test and read more document and code.
3) Save all windows before a system shutdown / logout / reboot.  But it should not work if someone press the physical power-off button.

**Comment by sojusnik** [comment]
> Duplicate issue: nlpsuge/xsession-manager#30

Only for X11, but your extension should work with both, X11 and Wayland.

> Restore saved windows after startup, should popup a dialog with a timeout (can be set in the Preferences?), user can click Yes to confirm or click Cancel to stop to restore in case no need to restore.

An option to choose between a dialogue and automatically restoring (without asking) would be great to have.

> Save all windows before a system shutdown / logout / reboot. But it should not work if someone press the physical power-off button.

You mean that after a proper shutdown it will work, but not after an “emergency” one, where one was pressing and holding the physical power button for some seconds?

**Comment by nlpsuge** [comment]
> Only for X11, but your extension should work with both, X11 and Wayland.

Sure. 

> An option to choose between a dialogue and automatically restoring (without asking) would be great to have.

Great idea. It should be an option in the References.

> You mean that after a proper shutdown it will work

Yes, by clicking those buttons:
![image](https://user-images.githubusercontent.com/2271720/147621568-1cd8f19b-4251-44e0-a0a8-75b1409e9fa2.png)

> , but not after an “emergency” one, where one was pressing and holding the physical power button for some seconds?

Yes. It should not work too if using non-GUI ways to quit Gnome, like using command `shutdown` or `pkill -KILL -u a-user-name`. I will just ignore these cases for now.

**Comment by Zefty** [comment]
Thanks for making this extension! The auto restore/save session would be a nice feature to have +1 from me for that as well.

**Comment by nlpsuge** [comment]
> 2) Restore window size and position. I have written this code but not well-tested, may not work at all. BTW, most app can restore their size and geometry on Gnome. Looks Shell API does not support this, not sure, I need to do more test and read documents and code.

Done. I have published a new release to support restoring window size and position :)

**Comment by nlpsuge** [comment]
> if this extension could save all windows before a system shutdown

There is a serious issue here for this target.  What if there are one or more apps can't be closed, such as the below two cases, what should this extension do?
1) Apps that are busy or its content has not been saved yet, like Gedit:
![image](https://user-images.githubusercontent.com/2271720/148987354-d8bb8aaf-01c4-44a8-be0e-a928242dabf3.png)

This extension won't close an app in such a case, data is more important after all.

2) If an app opens multiple windows, this extension won't close them by default.


What do you think? Any ideas?

For 2, I have a plan to add a whitelist in the Preferences, users put apps into this whitelist. And if an app is in the whitelist, this extension will close its windows one by one. The whitelist already exists in the code, gnome-terminal, Nautilus and SMplayer are in the whitelist. I think any apps that have no built-in session manager should be in the whitelist.

For 1, I'm still thinking ...


The above two cases will stop OS shutting down / rebooting / logging out after saving the session.

My goal is to close all apps safely.

What do you guys think?

**Comment by Zefty** [comment]
Hey im not too sure if this is a huge problem. 

Just before shutdown/reboot/logout, the extension should just activate. Basically, the feature should automate us pressing the "save open windows" button. 

Since those apps might prevent the shutdown/restart/logout, user can user to cancel or continue. If user cancels the shutdown/etc saves their work and then recommences shutdown/etc, then the extension should again automate the saving feature. This way whatever happens, the last state of apps should be saved. 

Let me know if this helps :smile:

**Comment by nlpsuge** [comment]
Hi everyone,

I would like to say that I have published the [pre-release: 14-beta.0](https://github.com/nlpsuge/gnome-shell-extension-another-window-session-manager/releases/tag/14-beta.0), you can download it from that page and install it for using the new feature. 

I'll publish a final release and upload it to the [https://extensions.gnome.org](https://extensions.gnome.org/extension/4709/another-window-session-manager/) in the following days.

I added a new button (<img src='https://github.com/nlpsuge/gnome-shell-extension-another-window-session-manager/raw/main/icons/toggle-on-autorestore-symbolic.svg' width="24" height="13">) in the popup menu to active a session, and restore it at startup. It supports restore a session with or without asking users.
![image](https://user-images.githubusercontent.com/2271720/163019716-2177ca8e-97b7-4a6c-9c4a-74a2326642be.png)


In the above menu, you can also click that filter button (<img src='https://github.com/nlpsuge/gnome-shell-extension-another-window-session-manager/raw/main/icons/autorestore-symbolic.svg' width="13" height="13">) to show only the auto-restore item. 
![image](https://user-images.githubusercontent.com/2271720/163021159-8a5bc130-9870-4303-a514-3edb16ffc433.png)


And a new settings page was added to Preferences to modify the delay, timer, or how to restore a session.
![image](https://user-images.githubusercontent.com/2271720/163020011-6df130b7-a3e7-4ce2-be7b-01ec5bb30304.png)


Restore a session with asking users:
![image](https://user-images.githubusercontent.com/2271720/163022100-26256446-1e6c-43a7-91f1-908ef72ae26c.png)


Cheers. :)

**Comment by nlpsuge** [comment]
> Duplicate issue: [nlpsuge/xsession-manager#30](https://github.com/nlpsuge/xsession-manager/issues/30)
> 
> The current released version can restore windows to their associated workspace.
> 
> My priority is:
> 
>     * [ ]  1)  Restore saved windows after startup, should popup a dialog with a timeout (can be set in the Preferences?), user can click Yes to confirm or click Cancel to stop to restore in case no need to restore.
> 
>     * [x]  2) Restore window size and position. I have written this code but not well-tested, may not work at all. BTW, most app can restore their size and geometry on Gnome. Looks Shell API does not support this, not sure, I need to do more test and read documents and code.
> 
>     * [ ]  3) Save all windows before a system shutdown / logout / reboot.  But it should not work if someone press the physical power-off button.

Tasks updated:

- [x] 1)  Restore saved windows after startup, should popup a dialog with a timeout (can be set in the Preferences?), user can click Yes to confirm or click Cancel to stop to restore in case no need to restore.
- [x] 2) Restore window size and position. I have written this code but not well-tested, may not work at all. BTW, most app can restore their size and geometry on Gnome. Looks Shell API does not support this, not sure, I need to do more test and read documents and code.
- [ ] 3) Save all windows before a system shutdown / logout / reboot.  But it should not work if someone press the physical power-off button.

**Comment by nlpsuge** [comment]
The feature of `restore at startup` has been released and approved in E.G.O. You should have received an update notification including this extension.

**Comment by nlpsuge** [comment]
> > Duplicate issue: [nlpsuge/xsession-manager#30](https://github.com/nlpsuge/xsession-manager/issues/30)
> > The current released version can restore windows to their associated workspace.
> > My priority is:
> > ```
> > * [ ]  1)  Restore saved windows after startup, should popup a dialog with a timeout (can be set in the Preferences?), user can click Yes to confirm or click Cancel to stop to restore in case no need to restore.
> > 
> > * [x]  2) Restore window size and position. I have written this code but not well-tested, may not work at all. BTW, most app can restore their size and geometry on Gnome. Looks Shell API does not support this, not sure, I need to do more test and read documents and code.
> > 
> > * [ ]  3) Save all windows before a system shutdown / logout / reboot.  But it should not work if someone press the physical power-off button.
> > ```
> 
> Tasks updated:
> 
>     * [x]  1)  Restore saved windows after startup, should popup a dialog with a timeout (can be set in the Preferences?), user can click Yes to confirm or click Cancel to stop to restore in case no need to restore.
> 
>     * [x]  2) Restore window size and position. I have written this code but not well-tested, may not work at all. BTW, most app can restore their size and geometry on Gnome. Looks Shell API does not support this, not sure, I need to do more test and read documents and code.
> 
>     * [ ]  3) Save all windows before a system shutdown / logout / reboot.  But it should not work if someone press the physical power-off button.

Tasks updated:

- [x] 1)  Restore saved windows after startup, should popup a dialog with a timeout (can be set in the Preferences?), user can click Yes to confirm or click Cancel to stop to restore in case no need to restore.
- [x] 2) Restore window size and position. I have written this code but not well-tested, may not work at all. BTW, most app can restore their size and geometry on Gnome. Looks Shell API does not support this, not sure, I need to do more test and read documents and code.
- [x] 3) Save all windows before a system shutdown / logout / reboot.  But it should not work if someone press the physical power-off button.

The third task is done by PR #67 and this issue will be closed automatically when  #67 is merged into the main branch. A new version will be pushed to https://extensions.gnome.org soon.
